import {
    Arcana0Fool,
    Arcana10Wheel,
    Arcana11Justice,
    Arcana12HangedMan,
    Arcana13Death,
    Arcana14Temperance,
    Arcana15Devil,
    Arcana16Tower,
    Arcana17Star,
    Arcana18Moon,
    Arcana19Sun,
    Arcana1Magus,
    Arcana20Judgement,
    Arcana21World,
    Arcana2HighPriestess,
    Arcana3Empress,
    Arcana4Emperor,
    Arcana5Hierophant,
    Arcana6Lovers,
    Arcana7Chariot,
    Arcana8Strength,
    Arcana9Hermit
} from './cards/major-arcana';
import {
    Coin1,
    Coin10,
    Coin2,
    Coin3,
    Coin4,
    Coin5,
    Coin6,
    Coin7,
    Coin8,
    Coin9,
    CoinKing,
    CoinKnight,
    CoinPage,
    CoinQueen
} from './cards/coins';
import {
    Cup1,
    Cup10,
    Cup2,
    Cup3,
    Cup4,
    Cup5,
    Cup6,
    Cup7,
    Cup8,
    Cup9,
    CupKing,
    CupKnight,
    CupPage,
    CupQueen
} from './cards/cups';
import React from 'react';
import type { SvgProps } from 'react-native-svg';
import {
    Sword1,
    Sword10,
    Sword2,
    Sword3,
    Sword4,
    Sword5,
    Sword6,
    Sword7,
    Sword8,
    Sword9,
    SwordKing,
    SwordKnight,
    SwordPage,
    SwordQueen
} from './cards/swords';
import {
    Wand1,
    Wand10,
    Wand2,
    Wand3,
    Wand4,
    Wand5,
    Wand6,
    Wand7,
    Wand8,
    Wand9,
    WandKing,
    WandKnight,
    WandPage,
    WandQueen
} from './cards/wands';

export type CardSvgProps = SvgProps & Record<string, unknown>;

const cardComponents: React.ComponentType<CardSvgProps>[] = [
    Arcana0Fool,
    Arcana1Magus,
    Arcana2HighPriestess,
    Arcana3Empress,
    Arcana4Emperor,
    Arcana5Hierophant,
    Arcana6Lovers,
    Arcana7Chariot,
    Arcana8Strength,
    Arcana9Hermit,
    Arcana10Wheel,
    Arcana11Justice,
    Arcana12HangedMan,
    Arcana13Death,
    Arcana14Temperance,
    Arcana15Devil,
    Arcana16Tower,
    Arcana17Star,
    Arcana18Moon,
    Arcana19Sun,
    Arcana20Judgement,
    Arcana21World,
    Wand1,
    Wand2,
    Wand3,
    Wand4,
    Wand5,
    Wand6,
    Wand7,
    Wand8,
    Wand9,
    Wand10,
    WandPage,
    WandKnight,
    WandQueen,
    WandKing,
    Cup1,
    Cup2,
    Cup3,
    Cup4,
    Cup5,
    Cup6,
    Cup7,
    Cup8,
    Cup9,
    Cup10,
    CupPage,
    CupKnight,
    CupQueen,
    CupKing,
    Sword1,
    Sword2,
    Sword3,
    Sword4,
    Sword5,
    Sword6,
    Sword7,
    Sword8,
    Sword9,
    Sword10,
    SwordPage,
    SwordKnight,
    SwordQueen,
    SwordKing,
    Coin1,
    Coin2,
    Coin3,
    Coin4,
    Coin5,
    Coin6,
    Coin7,
    Coin8,
    Coin9,
    Coin10,
    CoinPage,
    CoinKnight,
    CoinQueen,
    CoinKing
];

const useSvgCards = (
    card: number,
    props: CardSvgProps
): React.ReactElement<CardSvgProps> | null => {
    const Component = cardComponents[card];

    return Component ? <Component strokeWidth="1" fill="black" {...props} /> : null;
};

export default useSvgCards;
