name: Build and Deploy

on:
    workflow_dispatch:
    push:
        branches:
            - 'main'
        paths:
            - 'packages/ui/stories/**'

permissions:
    contents: read
    pages: write
    id-token: write

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v5
              with:
                  fetch-depth: 0
            - uses: actions/setup-node@v5
              with:
                  node-version: 24
            - run: corepack enable
            - uses: bitovi/github-actions-storybook-to-github-pages@v1.0.3
              with:
                  install_command: yarn install
                  build_command: yarn run build-storybook
                  path: 'packages/ui/storybook-static'
                  checkout: false
