name: Build and Deploy Storybook Pages

on:
    workflow_dispatch:
    push:
        branches:
            - 'main'
        paths:
            - 'packages/ui/stories/**'

permissions:
    contents: read
    pages: write
    id-token: write

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v5
              with:
                  fetch-depth: 0
            - uses: actions/setup-node@v5
              with:
                  node-version: 24
                  package-manager-cache: false
            - name: Prepare Yarn
              run: |
                corepack enable
                corepack prepare yarn@4.15.0 --activate
            - name: Build Types
              run: |  
                yarn install --immutable
                yarn build
            - uses: bitovi/github-actions-storybook-to-github-pages@v1.0.3
              with:
                  install_command: yarn install --immutable
                  build_command: yarn run build-storybook
                  path: 'packages/ui/storybook-static'
                  checkout: false
